### PR TITLE
Feature: Drone Radar

### PR DESCRIPTION
**Pull request by matejglejtek**
First production version of Drone Radar. 

The implementation consists of:
- setting user aircraft from aircraft detail, highlight user drone in list and map, uasid validation
- Drone Radar page with related settings such as distance, expiration time
- implementation of checking for alerts, checking is periodical using timer, alerts are outputed using a _stream_ of events
- on alerts, show top Flushbar with expiry timer, contains uasid or label, distance of nearby drone, centers on nearby drone on tap 
- if alert expired but aircraft is still nearby, warning icon shows on the toolbar, this was not in the specs but I added it myseft bcs i think there should be a way to show alert again if user misses it. not sure about the placement and style
- sending local notifications and managing notif. permissions
- change target android sdk to 33 because of new Android 13 permissions
- new onboarding part showcasing drone radar

TODO:

- [ ]  add FAQ about drone radar, connect to link from Drone Radar page

### CODE REVIEW

**Review by marianhlavac — CHANGES_REQUESTED** [review]
Phewww, this review won't be easy. It's looking really good, but it's not perfect. The addition of the alert icon in the heading is awesome. I've checked the functionality and UI so far, haven't checked code yet, so I'm sending some ongoing feedback:

- Had a run of the app when the functionality stopped working altogether. [Video footage of the run](https://user-images.githubusercontent.com/3010503/235982988-b11141ea-173a-4ff1-a976-158ea997e681.mp4). App needs to be reinstalled to start working again.
- Clicking on the "set as mine" sometimes gives "invalid length" even though the UASID is valid. The ID was _1596A346541F030_
- The radar icon has very low quality, there is no @2x or @3x asset in the project files
- Wrong font on the 'Radar is enabled' text in radar settings
- Notification card has inconsistent paddings, please match the UI design 
- Inconsistent labels in the radar settings. Some ends with colon, some does not

**Comment by matejglejtek** [comment]
I fixed some found issues:  replaced radar icon, fixed labels in settings, notification card changes, validation of shorter uasid.

**Review by marianhlavac — CHANGES_REQUESTED** [review]
**I have some feedback from the testing session we've performed today:**

- [x] To avoid confusion, consider also grounded drones for the proximity alerts. Later, if necessary, we'll add configuration option to use only airborne drones for the alerts.
- [ ] "Mine" drone shows always first in the list, but that might not always be what the user wants. Let's add "My drone position in list" configuration option to Preferences, with options "Default", "Always First", "Always Last", with "Always First" as the default selected option (current behavior).
- [x] Hide the "Data source" preference. This will be useful soon, but not for now. Can be kept commented-out in the code.
- [ ] Redesign the notification "warning icon", some users won't notice it. It should be more visible and pulse using animation. See the UI design or this [screenshot](https://github.com/dronetag/drone-scanner/assets/3010503/0127c5b9-d201-4e55-a378-adabb0c0ba1f).
- [x] Let's duplicate the link to the Radar preferences by adding "Drone Radar" item to the top-right main context menu (the three dots)
- [ ] Please use following asset for the radar icon. [radar-icon-asset.zip](https://github.com/dronetag/drone-scanner/files/11479461/radar-icon-asset.zip) Please adjust the size according to the other icons, not the exact file size. See the UI design.


**Issues that were still not fixed:**

- [ ] 'Radar is enabled' still has wrong font used

---

Android was tested, now it just requires some tests on iOS and then code review.

**Review by marianhlavac — CHANGES_REQUESTED** [review]
**Results of iOS tests**

* [ ] When app is left in background for a while, following appears in the logs and 
[the UI will crash completely](https://github.com/dronetag/drone-scanner/assets/3010503/d6d63f1c-58bd-47d3-abe0-f8cdef88076b).

<details>

```
[BackgroundTask] Background Task 191 ("Flutter debug task"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
flutter: Unhandled error occurred: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5127 pos 14: 'entry.currentState == _RouteLifecycle.popping': is not true. #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      NavigatorState.finalizeRoute (package:flutter/src/widgets/navigator.dart:5127:14)
#3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:80:18)
#4      FlushbarRoute.didPop (package:another_flushbar/flushbar_route.dart:392:18)
#5      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2978:16)
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3977:22)
#7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5003:7)
#8      FlushbarRoute._configureTimer.<anonymous closure> (package:another_flushbar/flushbar_route.dart:402:22)
#9      _rootRun (dart:async/zone.dart:1391:47)
#10     _CustomZone.run (dart:async/zone.dart:1301:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#13     _rootRun (dart:async/zone.dart:1399:13)
#14     _CustomZone.run (dart:async/zone.dart:1301:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
[Sentry] [debug] [SentrySystemEventBreadcrumbs:151] currentOrientation is unknown.
Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5234 pos 12: '!_debugLocked': is not true.
[Sentry] [debug] [SentryFileManager:417] Reading timestamp of last in foreground at: /var/mobile/Containers/Data/Application/E6EB1F71-B363-4B78-B1EA-CABB190E5ACD/Library/Caches/io.sentry/lastInForeground.timestamp
[Sentry] [debug] [SentryFileManager:354] Deleting session: /var/mobile/Containers/Data/Application/E6EB1F71-B363-4B78-B1EA-CABB190E5ACD/Library/Caches/io.sentry/session.current
flutter: Unhandled error occurred: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method. #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4347:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4361:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4396:12)
#3      Provider._inheritedElementOf (package:provider/src/provider.dart:339:38)
#4      Provider.of (package:provider/src/provider.dart:293:30)
#5      ReadContext.read (package:provider/src/provider.dart:649:21)
#6      _HomeBodyState.initState.<anonymous closure> (package:drone_scanner/widgets/mainpage/home_body.dart:53:27)
#7      _rootRunUnary (dart:async/zone.dart:1415:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#12     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[Sentry] [debug] [SentryHub:126] No session to end with timestamp.
[Sentry] [debug] [SentryFileManager:336] Writing session: /var/mobile/Containers/Data/Application/E6EB1F71-B363-4B78-B1EA-CABB190E5ACD/Library/Caches/io.sentry/session.current
[Sentry] [debug] Capturing session with status: {"errors":0,"status":"ok","started":"2023-05-26T13:42:18.476Z","did":"E77D37CC-F8E7-49F6-AFD5-4CDF739726A3","sid":"B1A26F8A-AEA1-4146-A91E-350932A9F857","init":true,"timestamp":"2023-05-26T13:42:18.480Z","attrs":{"release":"cz.dronetag.dronescanner@1.5.2+1.5.2","environment":"debug"},"seq":1}
[Sentry] [debug] [SentryClient:628] SDK disabled or no DSN set. Won't do anyting.
[Sentry] [debug] [SentryFileManager:407] Deleting LastInForeground at: /var/mobile/Containers/Data/Application/E6EB1F71-B363-4B78-B1EA-CABB190E5ACD/Library/Caches/io.sentry/lastInForeground.timestamp
```

</details>

* [ ] Putting the app in background produces following log line, which suggests that the "endBackgroundTask" is not being called: `[BackgroundTask] Background Task 191 ("Flutter debug task"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`


> Redesign the notification "warning icon", some users won't notice it. It should be more visible and pulse using animation. See the UI design or this [screenshot](https://github.com/dronetag/drone-scanner/assets/3010503/0127c5b9-d201-4e55-a378-adabb0c0ba1f).

* [x] The warning icon looks ok, but this was maybe communicated wrongly, but also the position should've change and it should be moved from the search bar to the right bar, as it's on the design.

**Comment by matejglejtek** [comment]
Alerts icon was moved to the right panel.

I did some testing and research and it seems that applications in background cannot be tested in debug mode very reliably, as the debug app has big demands and app is sometimes terminated. e.g. on Android, connection is sometimes lost after minimizing or app is restarted. I also found that the mentioned ios log appears only during debugging, it is mentioned [here](https://github.com/Baseflow/flutter-geolocator/issues/1028#issuecomment-1255980314) and [here](https://github.com/rmawatson/flutter_isolate/issues/91#issuecomment-972239463).

The` !debugLockError` (ui crash screenshot) should be fixed by delaying showing flushbar after resuming, error came from navigationg and showing flushbar at same time.

**Comment by marianhlavac** [comment]
> I did some testing and research and it seems that applications in background cannot be tested in debug mode very reliably

Ok, we'll push to TestFlight and revisit this in https://dronetag.atlassian.net/browse/DT-2407 before publishing the version.

**Comment by marianhlavac** [comment]
Please resolve the code analysis warnings before the next PR.

**Review by marianhlavac — APPROVED** [review]
We'll finish up this task as completed and finalize the feature by releasing the version to TestFlight and conducting more final tests before sending it to production.

**Pull request merged**
