### PR TITLE
ci: add asset upload to delivery

### PR DESCRIPTION
**Pull request by matejglejtek**
Add missing upload of assets to Github release to delivery workflow.

Solves https://github.com/dronetag/drone-scanner/issues/77.

DT-3177

### CODE REVIEW

**Comment by marianhlavac** [comment]
> Solves https://github.com/dronetag/drone-scanner/issues/77.

Btw the correct magic keyword is "fixes" or "closes" I think, "solves" won't work.

**Comment by matejglejtek** [comment]
> > Solves #77.
> 
> Btw the correct magic keyword is "fixes" or "closes" I think, "solves" won't work.

Well you are right 'solves' is not in the list of supported [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), but it still was somehow connected.

Screenshot 2024-06-24 at 9 36 30

**Comment by marianhlavac** [comment]
I did that manually 😅

**Review by marianhlavac — APPROVED** [review]
Cool skeleton 💀 , let's blow off the dust from this and merge it.

**Pull request merged**
