### PR TITLE
Upgraded Gradle config and Flutter packages

### PR DESCRIPTION
**Pull request by albertmoravec**
- Upgraded Android Gradle configuration style to the latest practice
- Bumped Gradle to 7.6.3
- Bumped Flutter packages

There are still Flutter packages which can be upgraded, but the process probably won't be straight-forward. After that we could try to drop dependency on Kotlin stdlib on Android, as I couldn't do it here.

TODO:
- Bump `flutter_opendroneid` and relock packages once https://github.com/dronetag/flutter-opendroneid/pull/26 is merged

### CODE REVIEW

**Comment by marianhlavac** [comment]
Checks still failing, need any help with that? I've also added @matejglejtek as reviewer.

**Comment by albertmoravec** [comment]
@marianhlavac Green now

**Comment by matejglejtek** [comment]
Podfile updated.

**Review by matejglejtek — APPROVED** [review]
lgtm

**Review by marianhlavac — APPROVED** [review]

**Pull request merged**
